
version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-for-jwt}
      - SUPABASE_URL=https://hodhzdfxagnvolvpyeai.supabase.co
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvZGh6ZGZ4YWdudm9sdnB5ZWFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4Nzc2NDUsImV4cCI6MjA1OTQ1MzY0NX0.TZopZVmzws8uVuAfZyonWSlCwjTTjI2rQj7fjlQIhI8
    restart: always
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
