// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzbpwtacoecwrzqpgbdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6YnB3dGFjb2Vjd3J6cXBnYmRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3OTU4MDQsImV4cCI6MjA1OTM3MTgwNH0.tyNW7WvnJiB5Vs53yqG2vWq1GG8UtTN-LqHSEj7nl54";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);